# COMMON
target_col: "HadHeartAttack"
metric: accuracy

# DATA TRANSFORMATION
data_transformation: "2" # id của data_transformation

# MODEL TRAINING
model_name: SGD
param_grid_model_desc:
      n_estimators: 400-600
      max_depth: 20-25
      subsample: 0.7-0.9
      learning_rate: 0.01-0.03

model_trainer_type: r # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal
N_ITER: 5 # số tổ hợp chọn khi chạy random search

# MODEL EVALUATION
evaluated_data_transformation: "10"
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      target_val_value: 97
      max_val_value: 100
      height_for_annot: 20
      dtick_y_value: 5
