# COMMON
target_col: do_get_Alzheimer
metric: accuracy

# DATA TRANSFORMATION
data_transformation: "500" # id của data_transformation

# MODEL TRAINING
model_name: XGB_5
param_grid_model_desc:
      n_estimators: 100-200-10
      max_depth: 10-15-1
      learning_rate: 0.01-0.03
      reg_alpha: 1-3
      reg_lambda: 1-3
      subsample: 0.7-0.9
      colsample_bytree: 0.7-0.9

model_trainer_type: r # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal
N_ITER: 5 # số tổ hợp chọn khi chạy random search

# MODEL EVALUATION
evaluated_data_transformation: "10"
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      target_val_value: 97
      max_val_value: 100
      height_for_annot: 20
      dtick_y_value: 5
