# COMMON
target_col: "HadHeartAttack"
metric: accuracy

# DATA TRANSFORMATION
data_transformation: "1_1" # id của data_transformation

# MODEL TRAINING
model_name: LR_0_1
param_grid_model_desc:
      C: 10-20-1

model_trainer_type: r # rcv: randomisedcv, gcv: gridcv, r: randomisedTrainVal, g: gridTrainVal
N_ITER: 5 # số tổ hợp chọn khi chạy random search

# MODEL EVALUATION
evaluated_data_transformation: "10"
evaluated_model_name: XGB_1

# MONITOR PLOT
monitor_plotter:
      target_val_value: 97
      max_val_value: 100
      height_for_annot: 20
      dtick_y_value: 5
